In [51]:
import tensorflow as tf
import os
import pandas as pd
import numpy as np

In [83]:
# Dataset loading
dataFrame = pd.read_csv('final_data_adj.csv')  # https://github.com/SusmitSekharBhakta/Stock-market-price-prediction/blob/main/final_data_adj.csv

In [85]:
dataFrame

,Date,Open,High,Low,Close,Adj Close,Volume,RSI,MACD,MACDsig,MACDhist,SMA,CCI,Aroon Up,Aroon Down,Sadj
0,2017-08-28,9907.150391,9925.750000,9882.000000,9912.799805,9912.799805,159600.0,55.406997,28.647258,28.317577,0.515867,12759.905212,24.363507,0.000000,0.000000,NaN
1,2017-08-29,9886.400391,9887.349609,9783.750000,9796.049805,9796.049805,173300.0,55.406997,28.647258,28.317577,0.515867,12759.905212,24.363507,0.000000,0.000000,162.055635
2,2017-08-30,9859.500000,9909.450195,9850.799805,9884.400391,9884.400391,157800.0,55.406997,28.647258,28.317577,0.515867,12759.905212,24.363507,0.000000,0.000000,-22.453545
3,2017-08-31,9905.700195,9925.099609,9856.950195,9917.900391,9917.900391,327700.0,55.406997,28.647258,28.317577,0.515867,12759.905212,24.363507,0.000000,0.000000,-9.197608
4,2017-09-01,9937.650391,9983.450195,9909.849609,9974.400391,9974.400391,157800.0,55.406997,28.647258,28.317577,0.515867,12759.905212,24.363507,0.000000,0.000000,5259.919641
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1820,2022-08-22,17682.900391,17690.050781,17467.349609,17490.699219,17490.699219,287600.0,53.212894,208.974422,276.509693,-67.535270,17407.845204,-30.373314,0.785714,0.071429,645.590963
1821,2022-08-23,17357.349609,17625.550781,17345.199219,17577.500000,17577.500000,285600.0,57.211306,187.134510,258.634656,-71.500146,17438.412435,-51.317372,0.714286,1.000000,2362.044621
1822,2022-08-24,17525.449219,17623.650391,17499.250000,17604.949219,17604.949219,262000.0,58.421409,170.080561,240.923837,-70.843276,17470.877409,-32.282705,0.642857,0.928571,4274.279466
1823,2022-08-25,17679.000000,17726.500000,17487.449219,17522.449219,17522.449219,230200.0,53.522099,148.199769,222.379023,-74.179254,17505.497396,-37.494292,0.571429,0.857143,3167.759103
1824,2022-08-26,17619.300781,17685.849609,17519.349609,17558.900391,17558.900391,266600.0,55.305540,132.275598,204.358338,-72.082740,17536.067383,-39.215379,0.500000,0.785714,785.840187

In [87]:
imputer = SimpleImputer(missing_values=np.nan)  # Handling missing values
dataFrame.drop(columns=['Date'], inplace=True)
print(dataFrame)
print("____________")
dataFrame = pd.DataFrame(imputer.fit_transform(dataFrame), columns=dataFrame.columns)
dataFrame = dataFrame.reset_index(drop=True)
print(dataFrame)
print("____________")
# Applying feature scaling
scaler = MinMaxScaler(feature_range=(0, 1))
df_scaled = scaler.fit_transform(dataFrame.to_numpy())
df_scaled = pd.DataFrame(df_scaled, columns=list(dataFrame.columns))
target_scaler = MinMaxScaler(feature_range=(0, 1))
df_scaled[['Open', 'Close']] = target_scaler.fit_transform(dataFrame[['Open', 'Close']].to_numpy())
df_scaled = df_scaled.astype(float)

              Open          High           Low         Close     Adj Close  \
0      9907.150391   9925.750000   9882.000000   9912.799805   9912.799805
1      9886.400391   9887.349609   9783.750000   9796.049805   9796.049805
2      9859.500000   9909.450195   9850.799805   9884.400391   9884.400391
3      9905.700195   9925.099609   9856.950195   9917.900391   9917.900391
4      9937.650391   9983.450195   9909.849609   9974.400391   9974.400391
...            ...           ...           ...           ...           ...
1820  17682.900391  17690.050781  17467.349609  17490.699219  17490.699219
1821  17357.349609  17625.550781  17345.199219  17577.500000  17577.500000
1822  17525.449219  17623.650391  17499.250000  17604.949219  17604.949219
1823  17679.000000  17726.500000  17487.449219  17522.449219  17522.449219
1824  17619.300781  17685.849609  17519.349609  17558.900391  17558.900391

        Volume        RSI        MACD     MACDsig   MACDhist           SMA  \
0     159600.0  55.406997   28.647258   28.317577   0.515867  12759.905212
1     173300.0  55.406997   28.647258   28.317577   0.515867  12759.905212
2     157800.0  55.406997   28.647258   28.317577   0.515867  12759.905212
3     327700.0  55.406997   28.647258   28.317577   0.515867  12759.905212
4     157800.0  55.406997   28.647258   28.317577   0.515867  12759.905212
...        ...        ...         ...         ...        ...           ...
1820  287600.0  53.212894  208.974422  276.509693 -67.535270  17407.845204
1821  285600.0  57.211306  187.134510  258.634656 -71.500146  17438.412435
1822  262000.0  58.421409  170.080561  240.923837 -70.843276  17470.877409
1823  230200.0  53.522099  148.199769  222.379023 -74.179254  17505.497396
1824  266600.0  55.305540  132.275598  204.358338 -72.082740  17536.067383

            CCI  Aroon Up  Aroon Down         Sadj
0     24.363507  0.000000    0.000000          NaN
1     24.363507  0.000000    0.000000   162.055635
2     24.363507  0.000000    0.000000   -22.453545
3     24.363507  0.000000    0.000000    -9.197608
4     24.363507  0.000000    0.000000  5259.919641
...         ...       ...         ...          ...
1820 -30.373314  0.785714    0.071429   645.590963
1821 -51.317372  0.714286    1.000000  2362.044621
1822 -32.282705  0.642857    0.928571  4274.279466
1823 -37.494292  0.571429    0.857143  3167.759103
1824 -39.215379  0.500000    0.785714   785.840187

[1825 rows x 15 columns]
____________
              Open          High           Low         Close     Adj Close  \
0      9907.150391   9925.750000   9882.000000   9912.799805   9912.799805
1      9886.400391   9887.349609   9783.750000   9796.049805   9796.049805
2      9859.500000   9909.450195   9850.799805   9884.400391   9884.400391
3      9905.700195   9925.099609   9856.950195   9917.900391   9917.900391
4      9937.650391   9983.450195   9909.849609   9974.400391   9974.400391
...            ...           ...           ...           ...           ...
1820  17682.900391  17690.050781  17467.349609  17490.699219  17490.699219
1821  17357.349609  17625.550781  17345.199219  17577.500000  17577.500000
1822  17525.449219  17623.650391  17499.250000  17604.949219  17604.949219
1823  17679.000000  17726.500000  17487.449219  17522.449219  17522.449219
1824  17619.300781  17685.849609  17519.349609  17558.900391  17558.900391

        Volume        RSI        MACD     MACDsig   MACDhist           SMA  \
0     159600.0  55.406997   28.647258   28.317577   0.515867  12759.905212
1     173300.0  55.406997   28.647258   28.317577   0.515867  12759.905212
2     157800.0  55.406997   28.647258   28.317577   0.515867  12759.905212
3     327700.0  55.406997   28.647258   28.317577   0.515867  12759.905212
4     157800.0  55.406997   28.647258   28.317577   0.515867  12759.905212
...        ...        ...         ...         ...        ...           ...
1820  287600.0  53.212894  208.974422  276.509693 -67.535270  17407.845204
1821  285600.0  57.211306  187.134510  258.634656 -71.500146  17438.412435
1822  262000.0  58.421409  170.080561  240.923837 -70.843276  17470.877409
1823  230200.0  53.522099  148.199769  222.379023 -74.179254  17505.497396
1824  266600.0  55.305540  132.275598  204.358338 -72.082740  17536.067383

            CCI  Aroon Up  Aroon Down         Sadj
0     24.363507  0.000000    0.000000  2935.220856
1     24.363507  0.000000    0.000000   162.055635
2     24.363507  0.000000    0.000000   -22.453545
3     24.363507  0.000000    0.000000    -9.197608
4     24.363507  0.000000    0.000000  5259.919641
...         ...       ...         ...          ...
1820 -30.373314  0.785714    0.071429   645.590963
1821 -51.317372  0.714286    1.000000  2362.044621
1822 -32.282705  0.642857    0.928571  4274.279466
1823 -37.494292  0.571429    0.857143  3167.759103
1824 -39.215379  0.500000    0.785714   785.840187

[1825 rows x 15 columns]
____________

In [36]:
# Single step dataset preparation
def singleStepSampler(df, window):
    xRes = []
    yRes = []
    for i in range(0, len(df) - window):
        res = []
        for j in range(0, window):
            r = []
            for col in df.columns:
                r.append(df[col][i + j])
            res.append(r)
        xRes.append(res)
        yRes.append(df[['Open', 'Close']].iloc[i + window].values)
    return np.array(xRes), np.array(yRes)

In [38]:
# Dataset splitting
SPLIT = 0.85
(xVal, yVal) = singleStepSampler(df_scaled, 20)
X_train = xVal[:int(SPLIT * len(xVal))]
y_train = yVal[:int(SPLIT * len(yVal))]
X_test = xVal[int(SPLIT * len(xVal)):]
y_test = yVal[int(SPLIT * len(yVal)):]

In [40]:
dataFrame

,Open,High,Low,Close,Adj Close,Volume,RSI,MACD,MACDsig,MACDhist,SMA,CCI,Aroon Up,Aroon Down,Sadj
0,9907.150391,9925.750000,9882.000000,9912.799805,9912.799805,159600.0,55.406997,28.647258,28.317577,0.515867,12759.905212,24.363507,0.000000,0.000000,2935.220856
1,9886.400391,9887.349609,9783.750000,9796.049805,9796.049805,173300.0,55.406997,28.647258,28.317577,0.515867,12759.905212,24.363507,0.000000,0.000000,162.055635
2,9859.500000,9909.450195,9850.799805,9884.400391,9884.400391,157800.0,55.406997,28.647258,28.317577,0.515867,12759.905212,24.363507,0.000000,0.000000,-22.453545
3,9905.700195,9925.099609,9856.950195,9917.900391,9917.900391,327700.0,55.406997,28.647258,28.317577,0.515867,12759.905212,24.363507,0.000000,0.000000,-9.197608
4,9937.650391,9983.450195,9909.849609,9974.400391,9974.400391,157800.0,55.406997,28.647258,28.317577,0.515867,12759.905212,24.363507,0.000000,0.000000,5259.919641
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1820,17682.900391,17690.050781,17467.349609,17490.699219,17490.699219,287600.0,53.212894,208.974422,276.509693,-67.535270,17407.845204,-30.373314,0.785714,0.071429,645.590963
1821,17357.349609,17625.550781,17345.199219,17577.500000,17577.500000,285600.0,57.211306,187.134510,258.634656,-71.500146,17438.412435,-51.317372,0.714286,1.000000,2362.044621
1822,17525.449219,17623.650391,17499.250000,17604.949219,17604.949219,262000.0,58.421409,170.080561,240.923837,-70.843276,17470.877409,-32.282705,0.642857,0.928571,4274.279466
1823,17679.000000,17726.500000,17487.449219,17522.449219,17522.449219,230200.0,53.522099,148.199769,222.379023,-74.179254,17505.497396,-37.494292,0.571429,0.857143,3167.759103
1824,17619.300781,17685.849609,17519.349609,17558.900391,17558.900391,266600.0,55.305540,132.275598,204.358338,-72.082740,17536.067383,-39.215379,0.500000,0.785714,785.840187

In [46]:
X_train.shape

(1534, 20, 15)

In [48]:
X_train

array([[[0.19986754, 0.17873669, 0.2168334 , ..., 0.        ,
         0.        , 0.17239144],
        [0.19795813, 0.17510287, 0.20784783, ..., 0.        ,
         0.        , 0.16717261],
        [0.19548275, 0.17719424, 0.21397995, ..., 0.        ,
         0.        , 0.16682538],
        ...,
        [0.21829455, 0.19773362, 0.23405913, ..., 0.92857143,
         0.28571429, 0.16426901],
        [0.21414898, 0.19665961, 0.23161732, ..., 0.85714286,
         0.21428571, 0.16755712],
        [0.21631912, 0.19844337, 0.23428935, ..., 1.        ,
         0.14285714, 0.16714143]],

       [[0.19795813, 0.17510287, 0.20784783, ..., 0.        ,
         0.        , 0.16717261],
        [0.19548275, 0.17719424, 0.21397995, ..., 0.        ,
         0.        , 0.16682538],
        [0.19973409, 0.17867514, 0.21454244, ..., 0.        ,
         0.        , 0.16685033],
        ...,
        [0.21414898, 0.19665961, 0.23161732, ..., 0.85714286,
         0.21428571, 0.16755712],
        [0.21631912, 0.19844337, 0.23428935, ..., 1.        ,
         0.14285714, 0.16714143],
        [0.21848926, 0.20022714, 0.23696138, ..., 1.        ,
         0.07142857, 0.16686776]],

       [[0.19548275, 0.17719424, 0.21397995, ..., 0.        ,
         0.        , 0.16682538],
        [0.19973409, 0.17867514, 0.21454244, ..., 0.        ,
         0.        , 0.16685033],
        [0.20267415, 0.18419685, 0.21938042, ..., 0.        ,
         0.        , 0.1767663 ],
        ...,
        [0.21631912, 0.19844337, 0.23428935, ..., 1.        ,
         0.14285714, 0.16714143],
        [0.21848926, 0.20022714, 0.23696138, ..., 1.        ,
         0.07142857, 0.16686776],
        [0.22065939, 0.2020109 , 0.2396334 , ..., 1.        ,
         0.14285714, 0.16619064]],

       ...,

       [[0.94343303, 0.94447376, 0.94723426, ..., 0.28571429,
         0.42857143, 0.16804298],
        [0.94585197, 0.94779172, 0.94575953, ..., 0.21428571,
         0.35714286, 0.17305346],
        [0.94827091, 0.95110968, 0.9442848 , ..., 0.14285714,
         0.28571429, 0.16265661],
        ...,
        [0.87847839, 0.90056777, 0.88758198, ..., 0.42857143,
         1.        , 0.1045405 ],
        [0.90316743, 0.90500594, 0.90019382, ..., 0.35714286,
         0.92857143, 0.16011253],
        [0.89095178, 0.90157561, 0.8999834 , ..., 0.28571429,
         0.85714286, 0.16495316]],

       [[0.94585197, 0.94779172, 0.94575953, ..., 0.21428571,
         0.35714286, 0.17305346],
        [0.94827091, 0.95110968, 0.9442848 , ..., 0.14285714,
         0.28571429, 0.16265661],
        [0.95233363, 0.95345638, 0.95772439, ..., 0.07142857,
         0.21428571, 0.3495898 ],
        ...,
        [0.90316743, 0.90500594, 0.90019382, ..., 0.35714286,
         0.92857143, 0.16011253],
        [0.89095178, 0.90157561, 0.8999834 , ..., 0.28571429,
         0.85714286, 0.16495316],
        [0.88372353, 0.8818028 , 0.86651045, ..., 0.21428571,
         1.        , 0.12533245]],

       [[0.94827091, 0.95110968, 0.9442848 , ..., 0.14285714,
         0.28571429, 0.16265661],
        [0.95233363, 0.95345638, 0.95772439, ..., 0.07142857,
         0.21428571, 0.3495898 ],
        [0.94212857, 0.94859718, 0.95150073, ..., 0.07142857,
         0.14285714, 0.1820109 ],
        ...,
        [0.89095178, 0.90157561, 0.8999834 , ..., 0.28571429,
         0.85714286, 0.16495316],
        [0.88372353, 0.8818028 , 0.86651045, ..., 0.21428571,
         1.        , 0.12533245],
        [0.87504453, 0.87566129, 0.8603128 , ..., 0.14285714,
         1.        , 0.18896625]]])